services:
  alledrogo.post.api:
    image: alledrogo.api
    container_name: Api
    build:
      context: .
      dockerfile: Bootstrapper/AlledrogO.Bootstrapper/Dockerfile
    ports:
      - "5000:8080"
  alledrogo.database:
    image: postgres:latest
    container_name: Postgres
    environment:
      - POSTGRES_DB=alledrogo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/alledrogo-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
