@AlledrogO.Post.Api_HostAddress = https://localhost:7056

GET {{AlledrogO.Post.Api_HostAddress}}/api/Post/a7cfed78-a5f2-4b28-8014-3109f4cdbc37
Accept: application/json

###

POST https://localhost:7056/api/User/login
Content-Type: application/json

{
  "email": "helluva@boss.com",
  "password": "Qwerty123@#",
  "rememberMe": true
}

###

POST https://localhost:7056/api/User/login
Content-Type: application/json

{
  "email": "client@wp.pl",
  "password": "Qwerty123@#",
  "rememberMe": true
}

###

PATCH https://localhost:7056/api/ChatUser
Content-Type: application/json

{
  "chatId": "a94ac6d2-1953-4e29-a2b9-5d9eee9a3459",
  "content": "IIIIILEEEEE"
}